# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35de0cd13e9df1a8d40c665ad187b5eeb6d88dcafd4e1a8fdc8ae9876544ccd3d44575304b51ded74a4f5020c9b7cf7b8e3b042cc29b253a1492f02d1d3a4b81

test:
  secret_key_base: f1c570febcb477be7a0149eb3ebc29b5907f57eecf790ac2da598a7dcab8a06be32a4a452bd442450fa5dbd8963606a9875062e1dc6482fbbecc960d4a257ec6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
